### PR TITLE
Add Reactive Oracle Client

### PR DESCRIPTION
**Pull request by tsegismont**
@cescoffier @jponge please review

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Thanks!

**Comment by tsegismont** [comment]
It fails because the Oracle client cannot be built with JDK8

**Comment by cescoffier** [comment]
MAke sense, I will update the CI

**Comment by tsegismont** [comment]
Thank you

**Review by cescoffier — APPROVED** [review]

**Pull request merged**
