### PR TITLE
Prepare release 2.11.0

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by jponge** [comment]
Let me check the effective POM

**Comment by jponge** [comment]
There's still a problem:

```xml
<dependencies>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-auth-jdbc</artifactId>
      <version>4.1.1</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-mutiny-vertx-core</artifactId>
      <version>2.10.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-mutiny-vertx-auth-common</artifactId>
      <version>2.10.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-mutiny-vertx-jdbc-client</artifactId>
      <version>2.10.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```

JUnit ends up in the effective POM

**Comment by cescoffier** [comment]
We s it because it’s a compile dependency of the vertx junit module?

**Comment by jponge** [comment]
No that's an extract from `mvn help:effective-pom -pl vertx-mutiny-clients/vertx-mutiny-auth-jdbc`

**Comment by jponge** [comment]
Oh wait, I'm on an old branch 🤦

**Comment by cescoffier** [comment]
Weird, the dependency tree looks good:

```
[INFO] --------< io.smallrye.reactive:smallrye-mutiny-vertx-auth-jdbc >--------
[INFO] Building SmallRye Mutiny - Vert.x Auth - JDBC 2.11.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ smallrye-mutiny-vertx-auth-jdbc ---
[INFO] io.smallrye.reactive:smallrye-mutiny-vertx-auth-jdbc:jar:2.11.0-SNAPSHOT
[INFO] +- io.vertx:vertx-auth-jdbc:jar:4.1.2:compile
[INFO] |  +- io.vertx:vertx-auth-common:jar:4.1.2:compile
[INFO] |  +- io.vertx:vertx-jdbc-client:jar:4.1.2:compile
[INFO] |  |  +- io.vertx:vertx-sql-client:jar:4.1.2:compile
[INFO] |  |  \- com.mchange:c3p0:jar:0.9.5.4:compile
[INFO] |  |     \- com.mchange:mchange-commons-java:jar:0.2.15:compile
[INFO] |  \- io.vertx:vertx-core:jar:4.1.2:compile
[INFO] |     +- io.netty:netty-common:jar:4.1.65.Final:compile
[INFO] |     +- io.netty:netty-buffer:jar:4.1.65.Final:compile
[INFO] |     +- io.netty:netty-transport:jar:4.1.65.Final:compile
[INFO] |     +- io.netty:netty-handler:jar:4.1.65.Final:compile
[INFO] |     |  \- io.netty:netty-codec:jar:4.1.65.Final:compile
[INFO] |     +- io.netty:netty-handler-proxy:jar:4.1.65.Final:compile
[INFO] |     |  \- io.netty:netty-codec-socks:jar:4.1.65.Final:compile
[INFO] |     +- io.netty:netty-codec-http:jar:4.1.65.Final:compile
[INFO] |     +- io.netty:netty-codec-http2:jar:4.1.65.Final:compile
[INFO] |     +- io.netty:netty-resolver:jar:4.1.65.Final:compile
[INFO] |     +- io.netty:netty-resolver-dns:jar:4.1.65.Final:compile
[INFO] |     |  \- io.netty:netty-codec-dns:jar:4.1.65.Final:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.12.4:compile
[INFO] +- io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.11.0-SNAPSHOT:compile
[INFO] |  +- io.smallrye.reactive:mutiny:jar:0.19.2:compile
[INFO] |  |  +- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  |  \- io.smallrye.common:smallrye-common-annotation:jar:1.6.0:compile
[INFO] |  +- io.smallrye.reactive:smallrye-mutiny-vertx-runtime:jar:2.11.0-SNAPSHOT:compile
[INFO] |  \- io.smallrye.reactive:vertx-mutiny-generator:jar:2.11.0-SNAPSHOT:compile
[INFO] |     \- io.vertx:vertx-codegen:jar:4.1.2:compile
[INFO] +- io.smallrye.reactive:smallrye-mutiny-vertx-auth-common:jar:2.11.0-SNAPSHOT:compile
[INFO] +- io.smallrye.reactive:smallrye-mutiny-vertx-jdbc-client:jar:2.11.0-SNAPSHOT:compile
[INFO] |  \- io.smallrye.reactive:smallrye-mutiny-vertx-sql-client:jar:2.11.0-SNAPSHOT:compile
[INFO] \- junit:junit:jar:4.13.2:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
```

**Comment by jponge** [comment]
Confirmed:

```xml
<dependencies>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-auth-jdbc</artifactId>
      <version>4.1.2</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-mutiny-vertx-core</artifactId>
      <version>2.11.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-mutiny-vertx-auth-common</artifactId>
      <version>2.11.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-mutiny-vertx-jdbc-client</artifactId>
      <version>2.11.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

**Review by jponge — APPROVED** [review]

**Comment by cescoffier** [comment]
ouf!

**Comment by cescoffier** [comment]
Ok, let's click the big green button.

**Comment by jponge** [comment]
> Ok, let's click the big green button.

Enjoy the ride

**Pull request merged**
