### PR TITLE
Add generation for the vertx-web-api-service module

### LINKED ISSUE #376: Add bindings for vertx-web-api-service
While working on a project leveraging OpenAPI and Vert.x Web Services, I realized that there was no corresponding Mutiny implementation for vertx-web-api-service and I was having to use `.getDelegate()` and having to create lambdas for Consumers wrapping around handlers. If `vertx-web-api-service` is going to be GA and a permanent addition to Vert.x, it would be great to have Mutiny bindings for it.

### PR DESCRIPTION
**Pull request by cescoffier**
Fix #376.﻿

### CODE REVIEW

**Comment by InfoSec812** [comment]
Thank you @cescoffier!!!

**Comment by ayhanap** [comment]
Should this have included the addition to the bom file(vertx-mutiny-clients-bom/pom.xml)?

**Comment by cescoffier** [comment]
Yes we should add it to the bom. Fancy a Pr?

**Comment by ayhanap** [comment]
Sure, will send one.

**Comment by ayhanap** [comment]
Sent with #607

**Pull request merged**
