### PR TITLE
Add the Vert.x HTTP proxy and the Vert.x Web Session stores (cookie and redis) modules

### LINKED ISSUE #662: mutiny binding for vertx http proxy
will there be a mutiny binding for the [vertx http proxy](https://vertx.io/docs/vertx-http-proxy/java/)?

### PR DESCRIPTION
**Pull request by cescoffier**
Fix #662 and #661

### CODE REVIEW

**Review by jponge — APPROVED** [review]

**Comment by jponge** [comment]
Should we add smoke tests like for some other modules?

**Comment by cescoffier** [comment]
@jponge the modules are very simple, so didn't plan to add tests.

**Comment by tsegismont** [comment]
Would you be interested in a contribution for Vert.x Web [session storage with Infinispan Client](https://how-to.vertx.io/web-session-infinispan-howto/) (i.e. without Vert.x clustering)

**Comment by cescoffier** [comment]
Ah yes! 

I checked the vertx web project only.

**Pull request merged**
